import React, { lazy, Suspense } from 'react';
import { BrowserRouter, MemoryRouter, Routes, Route, Navigate } from 'react-router-dom';
import Layout from './components/Layout';
import Home from './pages/Home';
import CV from './pages/CV';
import Research from './pages/Research';
import ResearchDetail from './pages/ResearchDetail';
import News from './pages/News';
import RouteEffects from './components/RouteEffects';

const Playground = lazy(() => import('./pages/Playground'));
const PlaygroundDetail = lazy(() => import('./pages/PlaygroundDetail'));
const SynthCanvasPage = lazy(() => import('./pages/SynthCanvasPage'));

export const AppContent: React.FC = () => (
  <>
    <RouteEffects />
    <Layout>
      <Suspense fallback={<div className="flex h-screen items-center justify-center text-neutral-500">Loading...</div>}>
        <Routes>
          <Route path="/" element={<Home />} />
          <Route path="/cv" element={<CV />} />
          <Route path="/research" element={<Research />} />
          <Route path="/research/:id" element={<ResearchDetail />} />
          <Route path="/news" element={<News />} />
          <Route path="/playground" element={<Playground />} />
          <Route path="/playground/:id" element={<PlaygroundDetail />} />
          <Route path="/synth" element={<SynthCanvasPage />} />
          <Route path="*" element={<Navigate to="/" replace />} />
        </Routes>
      </Suspense>
    </Layout>
  </>
);

// Utility to detect if we are running in a restricted environment (like a Blob URL)
// where modifying browser history throws a SecurityError.
const isRestrictedEnvironment = () => {
  try {
    return window.location.protocol === 'blob:';
  } catch (e) {
    return true;
  }
};

const App: React.FC = () => {
  // Use MemoryRouter for preview environments to prevent crashes.
  // Production routes have static index files generated by the build.
  const Router = isRestrictedEnvironment() ? MemoryRouter : BrowserRouter;

  return (
    <Router>
      <AppContent />
    </Router>
  );
};

export default App;
